name: Test CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
            - name: Publish Test Report
              if: always() # This ensures that the report is published even if the tests fail
              uses: dorny/test-reporter@v1
              with:
                name: 'Your Test Report Name'
                path: './test-results/*.xml' # Path where the JUnit test results are saved
                reporter: jest-junit 